### PR TITLE
GPLv2+ is not invalid

### PR DESCRIPTION
**Pull request by msmeissn**
GPLv2+ seems to valid in SPDX , so adjust the testcase

### CODE REVIEW

**Comment by coolo** [comment]
where on http://spdx.org/licenses/ do you see it? It's GPL-2.0+ - and it's deprecated

**Comment by msmeissn** [comment]
In the right column. Is the right column not the correct one=?

**Comment by coolo** [comment]
there are 4 columns and the most right one says 'License Text'. Are you talking about a different page?

**Comment by msmeissn** [comment]
i looked at license.opensuse.org, sorry

**Pull request closed without merging**
